#spring:
	#jpa:
    #	database: MYSQL
    #    hibernate:
    #        ddl-auto: validate

    #datasource:
    #    url: jdbc:mysql://mysql:3306/demo
    #    username: demo_user
    #    password: demo_pass
    #    driver-class-name: com.mysql.jdbc.Driver



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: p4SSW0rd
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
